  version: "3.9"

  services:
    artemis:
      image: apache/activemq-artemis:2.36.0
      container_name: artemis
      ports:
        - "61616:61616"   # JMS
        - "8161:8161"     # Web UI
      environment:
        ARTEMIS_USER: admin
        ARTEMIS_PASSWORD: admin
    notifier:
      build: ./gnivc-webhook-notifier
      depends_on:
        - artemis
      ports:
        - "8084:8084"

    webhook:
      build: ./gnivc-webhook-receiver
      depends_on:
        - artemis
      ports:
        - "8083:8083"