spring.application.name=notifier
telegram.bot-token=8280644322:AAEE8xXfoXdM0np12f4d5ejCT-oP7w9dMP0
telegram.chat-id=-1003870496812

server.port=8084

spring.artemis.mode=native
spring.artemis.broker-url=tcp://artemis:61616
spring.artemis.user=admin
spring.artemis.password=admin
