spring:
  application:
    name: webhook-receiver

  artemis:
    mode: native
    broker-url: tcp://artemis:61616
    user: admin
    password: admin

ru:
  gnivc:
    webhook:
      receiver:
        artemis:
          queue-address: git-actions-notify

server:
  port: 8083
