spring:
    application:
        name: webhook-receiver
    kafka:
        bootstrap-servers: kafka:29092
        producer:
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
    topic:
        base-prefix: git.
    default-key: default_notification_key

server:
    port: 8081