spring.application.name=webhook-receiver

server.port=8081

spring.kafka.bootstrap-servers=kafka:29092

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer