spring.application.name=webhook-receiver

server.port=8082

spring.kafka.bootstrap-servers=kafka:29092

telegram.bot.token=5882882891:AAFkzETeHYzry3liTHl_XhTr_iCCAXNAv_g
telegram.chat.id=936844493

spring.kafka.consumer.group-id=telegram-notifications
spring.kafka.consumer.auto-offset-reset=earliest